server.port=24110

# Postgres in docker-compose
spring.datasource.url=jdbc:postgresql://postgres:5432/distcomp
spring.datasource.username=postgres
spring.datasource.password=postgres

# discussion service in docker-compose network
discussion.base-url=http://discussion:24130

spring.data.redis.host=redis
spring.data.redis.port=6379
spring.cache.type=redis

app.jwt.secret=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
app.jwt.expiration-ms=86400000
