version: "3"
services:
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    mem_limit: 512m
 
  cassandra:
    image: cassandra:4.1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_BROADCAST_RPC_ADDRESS=127.0.0.1
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
 