server.port=24110
spring.application.name=publisher

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/distcomp
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# WebClient ??? discussion
discussion.base-url=http://localhost:24130/api/v1.0