// <auto-generated />
using System;
using BlogService.Infrastructure.PostgreSQL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlogService.Infrastructure.Migrations
{
    [DbContext(typeof(BlogServiceDbContext))]
    [Migration("20260317225616_InitialWithSchema")]
    partial class InitialWithSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("distcomp")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlogService.Domain.Entities.Comment<long>", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("StoryID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("StoryID");

                    b.ToTable("tbl_comments", "distcomp");
                });

            modelBuilder.Entity("BlogService.Domain.Entities.Sticker<long>", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("tbl_stickers", "distcomp");
                });

            modelBuilder.Entity("BlogService.Domain.Entities.Story<long>", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("tbl_story", "distcomp");
                });

            modelBuilder.Entity("BlogService.Domain.Entities.User<long>", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("tbl_user", "distcomp");
                });

            modelBuilder.Entity("tbl_StorySticker", b =>
                {
                    b.Property<long>("StickerID")
                        .HasColumnType("bigint");

                    b.Property<long>("StoryID")
                        .HasColumnType("bigint");

                    b.HasKey("StickerID", "StoryID");

                    b.HasIndex("StoryID");

                    b.ToTable("tbl_StorySticker", "distcomp");
                });

            modelBuilder.Entity("BlogService.Domain.Entities.Comment<long>", b =>
                {
                    b.HasOne("BlogService.Domain.Entities.Story<long>", "Story")
                        .WithMany("Comments")
                        .HasForeignKey("StoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("BlogService.Domain.Entities.Story<long>", b =>
                {
                    b.HasOne("BlogService.Domain.Entities.User<long>", "User")
                        .WithMany("Stories")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("tbl_StorySticker", b =>
                {
                    b.HasOne("BlogService.Domain.Entities.Sticker<long>", null)
                        .WithMany()
                        .HasForeignKey("StickerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogService.Domain.Entities.Story<long>", null)
                        .WithMany()
                        .HasForeignKey("StoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlogService.Domain.Entities.Story<long>", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("BlogService.Domain.Entities.User<long>", b =>
                {
                    b.Navigation("Stories");
                });
#pragma warning restore 612, 618
        }
    }
}
