// <auto-generated />
using System;
using BlogService.Infrastructure.PostgreSQL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlogService.Infrastructure.Migrations
{
    [DbContext(typeof(BlogServiceDbContext))]
    [Migration("20260507084216_AddCommentState")]
    partial class AddCommentState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("distcomp")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlogService.Domain.Entities.Comment<long>", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<long>("StoryID")
                        .HasColumnType("bigint")
                        .HasColumnName("story_id");

                    b.HasKey("ID");

                    b.HasIndex("StoryID");

                    b.ToTable("tbl_comment", "distcomp");
                });

            modelBuilder.Entity("BlogService.Domain.Entities.Sticker<long>", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("ID");

                    b.ToTable("tbl_sticker", "distcomp");
                });

            modelBuilder.Entity("BlogService.Domain.Entities.Story<long>", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("ID");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.HasIndex("UserID");

                    b.ToTable("tbl_story", "distcomp");
                });

            modelBuilder.Entity("BlogService.Domain.Entities.User<long>", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("ID");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("tbl_user", "distcomp");
                });

            modelBuilder.Entity("tbl_story_sticker", b =>
                {
                    b.Property<long>("sticker_id")
                        .HasColumnType("bigint");

                    b.Property<long>("story_id")
                        .HasColumnType("bigint");

                    b.HasKey("sticker_id", "story_id");

                    b.HasIndex("story_id");

                    b.ToTable("tbl_story_sticker", "distcomp");
                });

            modelBuilder.Entity("BlogService.Domain.Entities.Comment<long>", b =>
                {
                    b.HasOne("BlogService.Domain.Entities.Story<long>", "Story")
                        .WithMany("Comments")
                        .HasForeignKey("StoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("BlogService.Domain.Entities.Story<long>", b =>
                {
                    b.HasOne("BlogService.Domain.Entities.User<long>", "User")
                        .WithMany("Stories")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("tbl_story_sticker", b =>
                {
                    b.HasOne("BlogService.Domain.Entities.Sticker<long>", null)
                        .WithMany()
                        .HasForeignKey("sticker_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogService.Domain.Entities.Story<long>", null)
                        .WithMany()
                        .HasForeignKey("story_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlogService.Domain.Entities.Story<long>", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("BlogService.Domain.Entities.User<long>", b =>
                {
                    b.Navigation("Stories");
                });
#pragma warning restore 612, 618
        }
    }
}
