services:
  postgres:
    image: 'postgres:15-alpine'
    environment:
      - 'POSTGRES_DB=distcomp'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
  cassandra:
    image: 'cassandra:4.1'
    ports:
      - '9042:9042'
