"""add cascade deletes for writer article note

Revision ID: 4cba09790fa7
Revises: 796a9e418fe8
Create Date: 2026-03-24 18:00:44.603838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cba09790fa7'
down_revision: Union[str, Sequence[str], None] = '796a9e418fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tbl_article_writer_id_fkey'), 'tbl_article', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_article', 'tbl_writer', ['writer_id'], ['id'], source_schema='distcomp', referent_schema='distcomp', ondelete='CASCADE')
    op.drop_constraint(op.f('tbl_article_marker_article_id_fkey'), 'tbl_article_marker', type_='foreignkey')
    op.drop_constraint(op.f('tbl_article_marker_marker_id_fkey'), 'tbl_article_marker', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_article_marker', 'tbl_article', ['article_id'], ['id'], source_schema='distcomp', referent_schema='distcomp', ondelete='CASCADE')
    op.create_foreign_key(None, 'tbl_article_marker', 'tbl_marker', ['marker_id'], ['id'], source_schema='distcomp', referent_schema='distcomp', ondelete='CASCADE')
    op.drop_constraint(op.f('tbl_note_article_id_fkey'), 'tbl_note', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_note', 'tbl_article', ['article_id'], ['id'], source_schema='distcomp', referent_schema='distcomp', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_note', schema='distcomp', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_note_article_id_fkey'), 'tbl_note', 'tbl_article', ['article_id'], ['id'])
    op.drop_constraint(None, 'tbl_article_marker', schema='distcomp', type_='foreignkey')
    op.drop_constraint(None, 'tbl_article_marker', schema='distcomp', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_article_marker_marker_id_fkey'), 'tbl_article_marker', 'tbl_marker', ['marker_id'], ['id'])
    op.create_foreign_key(op.f('tbl_article_marker_article_id_fkey'), 'tbl_article_marker', 'tbl_article', ['article_id'], ['id'])
    op.drop_constraint(None, 'tbl_article', schema='distcomp', type_='foreignkey')
    op.create_foreign_key(op.f('tbl_article_writer_id_fkey'), 'tbl_article', 'tbl_writer', ['writer_id'], ['id'])
    # ### end Alembic commands ###
