package com.blog;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
public class DatabaseInitializer implements CommandLineRunner {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Override
    public void run(String... args) throws Exception {
        try {
            System.out.println("Database initialization started...");

            // Create tables if they don't exist
            createTables();

            System.out.println("Database initialization completed successfully");

        } catch (Exception e) {
            System.err.println("Error initializing database: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void createTables() {
        // Create tbl_writer table
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS distcomp.tbl_writer (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created TIMESTAMP NOT NULL,
                modified TIMESTAMP NOT NULL,
                firstname VARCHAR(50) NOT NULL,
                lastname VARCHAR(50) NOT NULL,
                login VARCHAR(50) NOT NULL UNIQUE,
                password VARCHAR(255) NOT NULL
            )
            """);

        // Create tbl_tag table
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS distcomp.tbl_tag (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created TIMESTAMP NOT NULL,
                modified TIMESTAMP NOT NULL,
                name VARCHAR(50) NOT NULL UNIQUE
            )
            """);

        // Create tbl_article table
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS distcomp.tbl_article (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created TIMESTAMP NOT NULL,
                modified TIMESTAMP NOT NULL,
                writer_id BIGINT NOT NULL,
                title VARCHAR(200) NOT NULL,
                content TEXT NOT NULL,
                FOREIGN KEY (writer_id) REFERENCES distcomp.tbl_writer(id) ON DELETE CASCADE
            )
            """);

        // Create tbl_reaction table
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS distcomp.tbl_reaction (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created TIMESTAMP NOT NULL,
                modified TIMESTAMP NOT NULL,
                article_id BIGINT NOT NULL,
                content TEXT NOT NULL,
                FOREIGN KEY (article_id) REFERENCES distcomp.tbl_article(id) ON DELETE CASCADE
            )
            """);

        // Create tbl_article_tag junction table
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS distcomp.tbl_article_tag (
                article_id BIGINT NOT NULL,
                tag_id BIGINT NOT NULL,
                PRIMARY KEY (article_id, tag_id),
                FOREIGN KEY (article_id) REFERENCES distcomp.tbl_article(id) ON DELETE CASCADE,
                FOREIGN KEY (tag_id) REFERENCES distcomp.tbl_tag(id) ON DELETE CASCADE
            )
            """);

        System.out.println("All tables created successfully in schema distcomp");
    }
}