server.address=localhost
server.port=24110
server.servlet.context-path=/
spring.application.name=TrainingApplication

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/distcomp?currentSchema=dictcomp
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.default-schema=dictcomp
spring.liquibase.liquibase-schema=dictcomp

# JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=validate  
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

discussion.base-url=http://localhost:24130/api/v1.0