"""initial: create tables

Revision ID: a4a72cf13809
Revises: 
Create Date: 2026-03-06 22:16:01.091518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4a72cf13809'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_marker',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='distcomp'
    )
    op.create_table('tbl_writer',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('login', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('firstname', sa.Text(), nullable=True),
    sa.Column('lastname', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login'),
    schema='distcomp'
    )
    op.create_table('tbl_article',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('writer_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['writer_id'], ['distcomp.tbl_writer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='distcomp'
    )
    op.create_table('tbl_article_marker',
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('marker_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['distcomp.tbl_article.id'], ),
    sa.ForeignKeyConstraint(['marker_id'], ['distcomp.tbl_marker.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'marker_id'),
    schema='distcomp'
    )
    op.create_table('tbl_note',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['distcomp.tbl_article.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='distcomp'
    )
    op.drop_table('alembic_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.drop_table('tbl_note', schema='distcomp')
    op.drop_table('tbl_article_marker', schema='distcomp')
    op.drop_table('tbl_article', schema='distcomp')
    op.drop_table('tbl_writer', schema='distcomp')
    op.drop_table('tbl_marker', schema='distcomp')
    # ### end Alembic commands ###
