server:
  port: 24130
spring:
  application:
    name: discussion
  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: distcomp
    schema-action: create-if-not-exists
    local-datacenter: datacenter1
  liquibase:
    url: cassandra://localhost:9042/distcomp?compliancemode=Liquibase&localDatacenter=datacenter1
    change-log: classpath:db/changelog/main-changelog.yml
    enabled: true
    driver-class-name: org.liquibase.ext.cassandra.driver.CassandraDriver
logging:
  level:
    liquibase: DEBUG