spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
server:
  address: localhost
  port: 24110
  api:
    base-path:
      v1: "/api/v1.0"
      v2: "/api/v2.0"
management:
  endpoints:
    web:
      exposure:
        include: mappings
