server.address=localhost
server.port=24110
server.servlet.context-path=/
spring.application.name=TrainingApplication


spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.default-schema=distcomp
spring.liquibase.liquibase-schema=distcomp